### ISSUE TITLE
Redundant with gleam-community/colour

### ISSUE THREAD

**Issue by ghivert** [brunoti/lumiere#3]
Hi !

Maybe what you're looking for in the end (or at least to take inspiration) is [gleam-community/colour](https://hexdocs.pm/gleam_community_colour/gleam_community/colour.html).

**Comment by brunoti** [comment]
Awesome! I'll probably keep working on this (because it's fun) but it's nice to have some good inspiration. Thanks!

**Comment by ghivert** [comment]
Yes! My idea was more to give you inspiration than discourages you, as long as it's fun for you, keep working on it! 😉
